version: "3.8"

services:
  el-mago-postgres:
    container_name: el-mago-postgres
    image: postgres:15-alpine

    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - el-mago-network

  el-mago-redis:
    image: redis:7-alpine
    container_name: el-mago-bank-redis
    command: >
      --requirepass ${REDIS_PASSWORD}

    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - el-mago-network

networks:
  el-mago-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
