export enum KEY_INJECTION {
  USER_REPOSITORY_CONTRACT = 'USER_REPOSITORY_CONTRACT',
  AFFILIATE_REPOSITORY_CONTRACT = 'AFFILIATE_REPOSITORY_CONTRACT',
  IMAGE_REPOSITORY_CONTRACT = 'IMAGE_REPOSITORY_CONTRACT ',
  ITEM_REPOSITORY_CONTRACT = 'ITEM_REPOSITORY_CONTRACT',
  CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY',
  CART_REPOSITORY = 'CART_REPOSITORY',
  ORDER_REPOSITORY = 'ORDER_REPOSITORY',
}
