export enum TABLE {
  user = 'user',
  affiliate = 'affiliate',
  affiliate_queue = 'affiliate_queue',
  item = 'item',
  image = 'image',
  category = 'category',
  order = 'order',
  cart = 'cart',
  cart_item = 'cart_item',
  order_status = 'order_status',
  order_item = 'order_item',
  order_in_progress = 'order_in_progress',
  proof_of_delivery = 'proof_of_delivery',
}
